# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libgit2-dev
      - texlive-fonts-extra
#r_github_packages:
#  - crsh/papaja
#r_packages:
#  - broom
#    - os: osx
#      osx_image: xcode11.2
#      r: release

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: oldrel
    - os: linux
      r: devel
