# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libgit2-dev
      - texlive-fonts-extra
#r_github_packages:
#  - crsh/papaja
#r_packages:
#  - broom

matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release
      
# macOS 10.12 version
osx_image: xcode9.2

